//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Lessons = new HashSet<Lesson>();
        }
    
        public string course_id { get; set; }
        public string course_name { get; set; }
        public System.DateTime update_date { get; set; }
        public string description { get; set; }
        public decimal duration { get; set; }
        public decimal user_id { get; set; }
        public string role { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}
